/** Job Market Simulation — main page (003) */
import { useState, useEffect, useCallback, useRef } from 'react'
import { api } from '../services/api'
import type { JobBoardLoad, Vehicle, Driver, Quote, ScoreBreakdown } from '../lib/jobmarket/types'
import { getFieldLabel, getVehicleTypeLabel } from '../lib/jobmarket/displayNames'
import { JobBoard } from '../components/jobmarket/JobBoard'
import { JobDetails } from '../components/jobmarket/JobDetails'
import { GenerateJobs } from '../components/jobmarket/GenerateJobs'
import { FleetManagement } from '../components/jobmarket/FleetManagement'
import { FleetProfile } from '../components/jobmarket/FleetProfile'
import { QuoteForm } from '../components/jobmarket/QuoteForm'
import { QuoteHistory } from '../components/jobmarket/QuoteHistory'
import { UKMap } from '../components/jobmarket/UKMap'

type Role = 'fleet' | 'load_poster'
type FleetTab = 'operations' | 'fleet_setup'
type OpsView = 'table' | 'map'

export function JobMarket() {
  const [role, setRole] = useState<Role>('fleet')
  const [fleetTab, setFleetTab] = useState<FleetTab>('operations')
  const [opsView, setOpsView] = useState<OpsView>('map')
  const [jobs, setJobs] = useState<JobBoardLoad[]>([])
  const [selectedJobId, setSelectedJobId] = useState<string | null>(null)
  const [vehicles, setVehicles] = useState<Vehicle[]>([])
  const [drivers, setDrivers] = useState<Driver[]>([])
  const [quotes, setQuotes] = useState<(Quote & { score_breakdown?: ScoreBreakdown })[]>([])
  const [hubs, setHubs] = useState<Record<string, { lat: number; lng: number }>>({})
  const [loading, setLoading] = useState(true)
  const [quotesLoading, setQuotesLoading] = useState(true)
  const [profileRefresh, setProfileRefresh] = useState(0)
  const autoGenerated = useRef(false)

  const fetchJobs = useCallback(async () => {
    setLoading(true)
    try {
      const { jobs: j } = await api.jobmarket.getJobs('posted')
      setJobs(j || [])
      if (selectedJobId && !j?.some((x) => x.load_id === selectedJobId)) {
        setSelectedJobId(null)
      }
    } catch {
      setJobs([])
    } finally {
      setLoading(false)
    }
  }, [selectedJobId])

  const fetchProfileAndQuotes = useCallback(async () => {
    setQuotesLoading(true)
    try {
      const [profileRes, quotesRes] = await Promise.all([
        api.jobmarket.getProfile(),
        api.jobmarket.getQuoteHistory(),
      ])
      setVehicles(profileRes.vehicles || [])
      setDrivers(profileRes.drivers || [])
      setQuotes(quotesRes.quotes || [])
      setProfileRefresh((r) => r + 1)
    } catch {
      setVehicles([])
      setDrivers([])
      setQuotes([])
    } finally {
      setQuotesLoading(false)
    }
  }, [])

  useEffect(() => {
    fetchJobs()
  }, [fetchJobs])

  useEffect(() => {
    api.jobmarket.getHubs().then((r) => {
      const map: Record<string, { lat: number; lng: number }> = {}
      for (const h of r.hubs) {
        map[h.city] = { lat: h.lat, lng: h.lng }
      }
      setHubs(map)
    }).catch(() => {})
  }, [])

  useEffect(() => {
    if (role === 'fleet') {
      fetchProfileAndQuotes()
    } else {
      setQuotesLoading(false)
    }
  }, [role, fetchProfileAndQuotes])

  // Auto-generate 20 jobs + 10 vehicles/drivers on first load when empty
  useEffect(() => {
    if (autoGenerated.current || loading) return
    if (jobs.length === 0 && vehicles.length === 0) {
      autoGenerated.current = true
      ;(async () => {
        try {
          await Promise.all([
            api.jobmarket.generateJobs(20),
            api.jobmarket.generateFleet(10, 10),
          ])
          await Promise.all([fetchJobs(), fetchProfileAndQuotes()])
        } catch {
          // ignore — user can manually generate
        }
      })()
    }
  }, [loading, jobs.length, vehicles.length, fetchJobs, fetchProfileAndQuotes])

  const selectedJob = jobs.find((j) => j.load_id === selectedJobId) ?? null

  const handleGenerate = async (count: number) => {
    await api.jobmarket.generateJobs(count)
    await fetchJobs()
  }

  const handleQuoteSubmitted = () => {
    fetchJobs()
    fetchProfileAndQuotes()
  }

  const handleDeleteQuote = async (quoteId: string) => {
    try {
      await api.jobmarket.deleteQuote(quoteId)
      fetchProfileAndQuotes()
    } catch {
      // ignore
    }
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-semibold text-[var(--md-text-primary)]">Job Market</h1>
        <div className="flex rounded border border-black/12 overflow-hidden">
          <button
            type="button"
            onClick={() => setRole('fleet')}
            className={`px-4 py-2 text-sm font-medium ${
              role === 'fleet'
                ? 'bg-primary text-white'
                : 'bg-white text-[var(--md-text-secondary)] hover:bg-black/4'
            }`}
            aria-pressed={role === 'fleet'}
            aria-label="Fleet Operator view"
          >
            Fleet Operator
          </button>
          <button
            type="button"
            onClick={() => setRole('load_poster')}
            className={`px-4 py-2 text-sm font-medium ${
              role === 'load_poster'
                ? 'bg-primary text-white'
                : 'bg-white text-[var(--md-text-secondary)] hover:bg-black/4'
            }`}
            aria-pressed={role === 'load_poster'}
            aria-label="Load Poster view"
          >
            Load Poster
          </button>
        </div>
      </div>

      {role === 'load_poster' ? (
        <div className="space-y-4">
          <GenerateJobs onGenerate={handleGenerate} />
          <JobBoard
            jobs={jobs}
            selectedJobId={null}
            onSelectJob={() => {}}
            onRefresh={fetchJobs}
          />
        </div>
      ) : (
        <div className="space-y-4">
          {/* Fleet Operator tabs */}
          <div className="flex items-center justify-between border-b border-black/10">
            <div className="flex gap-1">
              <button
                type="button"
                onClick={() => setFleetTab('operations')}
                className={`px-4 py-2.5 text-sm font-medium transition-colors ${
                  fleetTab === 'operations'
                    ? 'text-primary border-b-2 border-primary -mb-px'
                    : 'text-[rgba(0,0,0,0.6)] hover:text-[rgba(0,0,0,0.87)]'
                }`}
                aria-pressed={fleetTab === 'operations'}
                aria-label="Operations tab: job board and map"
              >
                Operations
              </button>
              <button
                type="button"
                onClick={() => setFleetTab('fleet_setup')}
                className={`px-4 py-2.5 text-sm font-medium transition-colors ${
                  fleetTab === 'fleet_setup'
                    ? 'text-primary border-b-2 border-primary -mb-px'
                    : 'text-[rgba(0,0,0,0.6)] hover:text-[rgba(0,0,0,0.87)]'
                }`}
                aria-pressed={fleetTab === 'fleet_setup'}
                aria-label="Fleet Setup tab: profile and vehicles"
              >
                Fleet Setup
              </button>
            </div>

            {/* Table / Map toggle — only visible on Operations tab */}
            {fleetTab === 'operations' && (
              <div className="flex rounded border border-black/12 overflow-hidden mr-1 mb-1">
                <button
                  type="button"
                  onClick={() => setOpsView('table')}
                  className={`px-3 py-1.5 text-xs font-medium flex items-center gap-1.5 ${
                    opsView === 'table'
                      ? 'bg-primary text-white'
                      : 'bg-white text-[var(--md-text-secondary)] hover:bg-black/4'
                  }`}
                  aria-pressed={opsView === 'table'}
                  aria-label="View job board as table"
                >
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/></svg>
                  Table
                </button>
                <button
                  type="button"
                  onClick={() => setOpsView('map')}
                  className={`px-3 py-1.5 text-xs font-medium flex items-center gap-1.5 ${
                    opsView === 'map'
                      ? 'bg-primary text-white'
                      : 'bg-white text-[var(--md-text-secondary)] hover:bg-black/4'
                  }`}
                  aria-pressed={opsView === 'map'}
                  aria-label="View job board on map"
                >
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><path d="M1 6v16l7-4 8 4 7-4V2l-7 4-8-4-7 4z"/><path d="M8 2v16"/><path d="M16 6v16"/></svg>
                  Map
                </button>
              </div>
            )}
          </div>

          {/* Tab content */}
          {fleetTab === 'operations' ? (
            <div className="space-y-4">
              {opsView === 'table' ? (
              /* ── TABLE VIEW ── */
              <>
                <div className="grid grid-cols-1 lg:grid-cols-5 gap-4">
                  {/* Left: Job Board */}
                  <div className="lg:col-span-3">
                    <JobBoard
                      jobs={jobs}
                      selectedJobId={selectedJobId}
                      onSelectJob={setSelectedJobId}
                      onRefresh={fetchJobs}
                    />
                  </div>

                  {/* Right: Map + Job Details + Quote Form */}
                  <div className="lg:col-span-2 space-y-4">
                    <div className="rounded border border-black/12 bg-white overflow-hidden">
                      <UKMap
                        job={selectedJob}
                        vehicles={vehicles}
                        hubs={hubs}
                        className="h-48 w-full"
                      />
                    </div>

                    {loading ? (
                      <p className="text-[var(--md-text-secondary)]">Loading...</p>
                    ) : (
                      <JobDetails
                        job={selectedJob}
                        jobsAtSameCity={
                          selectedJob
                            ? [...jobs.filter((j) => j.collection_city === selectedJob.collection_city)].sort(
                                (a, b) => a.delivery_city.localeCompare(b.delivery_city) || a.load_id.localeCompare(b.load_id)
                              )
                            : undefined
                        }
                        onSelectJob={setSelectedJobId}
                        quoteFormSlot={
                          selectedJob && (
                            <QuoteForm
                              job={selectedJob}
                              vehicles={vehicles}
                              drivers={drivers}
                              onSubmitted={handleQuoteSubmitted}
                            />
                          )
                        }
                      />
                    )}
                  </div>
                </div>
                <QuoteHistory quotes={quotes} loading={quotesLoading} onRefresh={fetchProfileAndQuotes} onDeleteQuote={handleDeleteQuote} />
              </>
            ) : (
              /* ── MAP VIEW ── */
              <div className="space-y-4">
                <div className="relative rounded border border-black/12 bg-white overflow-hidden">
                  <UKMap
                    job={selectedJob}
                    jobs={jobs}
                    vehicles={vehicles}
                    hubs={hubs}
                    className="h-[70vh] w-full"
                    onSelectJob={setSelectedJobId}
                    selectedJobId={selectedJobId}
                  />

                  {/* Floating job details + quote panel */}
                  {selectedJob && (() => {
                    const jobsAtSameCity = jobs
                      .filter((j) => j.collection_city === selectedJob.collection_city)
                      .sort((a, b) => a.delivery_city.localeCompare(b.delivery_city) || a.load_id.localeCompare(b.load_id))
                    const sameCityIndex = jobsAtSameCity.findIndex((j) => j.load_id === selectedJobId)
                    const hasMultipleAtLocation = jobsAtSameCity.length > 1
                    const goPrev = () => {
                      if (sameCityIndex <= 0) return
                      setSelectedJobId(jobsAtSameCity[sameCityIndex - 1].load_id)
                    }
                    const goNext = () => {
                      if (sameCityIndex < 0 || sameCityIndex >= jobsAtSameCity.length - 1) return
                      setSelectedJobId(jobsAtSameCity[sameCityIndex + 1].load_id)
                    }
                    return (
                    <div className="absolute top-3 right-3 z-[1000] w-80 max-h-[calc(70vh-24px)] overflow-y-auto bg-white rounded-lg shadow-xl border border-black/12">
                      {/* Panel header */}
                      <div className="sticky top-0 bg-white border-b border-black/8 px-4 py-3 flex items-center justify-between">
                        <div className="min-w-0">
                          <h4 className="font-semibold text-sm truncate">
                            {selectedJob.collection_city} &rarr; {selectedJob.delivery_city}
                          </h4>
                          <p className="text-xs text-[var(--md-text-secondary)]">
                            {selectedJob.distance_km} km · {selectedJob.required_vehicle_type ? getVehicleTypeLabel(selectedJob.required_vehicle_type) : '-'}
                            {selectedJob.adr_required ? ' · ADR' : ''}
                          </p>
                        </div>
                        <button
                          type="button"
                          onClick={() => setSelectedJobId(null)}
                          className="text-[var(--md-text-secondary)] hover:text-[var(--md-text-primary)] p-1 shrink-0"
                          aria-label="Close"
                        >
                          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M18 6L6 18M6 6l12 12"/></svg>
                        </button>
                      </div>

                      {/* Switch between loads at same location */}
                      {hasMultipleAtLocation && (
                        <div className="sticky top-0 bg-white border-b border-black/8 px-4 py-2 flex items-center justify-between gap-2">
                          <span className="text-xs text-[var(--md-text-secondary)]">
                            {sameCityIndex + 1} of {jobsAtSameCity.length} at {selectedJob.collection_city}
                          </span>
                          <div className="flex items-center gap-0.5">
                            <button
                              type="button"
                              onClick={goPrev}
                              disabled={sameCityIndex <= 0}
                              className="p-1.5 rounded text-[var(--md-text-secondary)] hover:bg-black/6 hover:text-[var(--md-text-primary)] disabled:opacity-40 disabled:pointer-events-none"
                              aria-label="Previous job"
                            >
                              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M15 18l-6-6 6-6"/></svg>
                            </button>
                            <button
                              type="button"
                              onClick={goNext}
                              disabled={sameCityIndex >= jobsAtSameCity.length - 1}
                              className="p-1.5 rounded text-[var(--md-text-secondary)] hover:bg-black/6 hover:text-[var(--md-text-primary)] disabled:opacity-40 disabled:pointer-events-none"
                              aria-label="Next job"
                            >
                              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M9 18l6-6-6-6"/></svg>
                            </button>
                          </div>
                        </div>
                      )}

                      {/* Job details */}
                      <div className="px-4 py-3 border-b border-black/5">
                        <dl className="grid grid-cols-2 gap-1.5 text-xs">
                          <dt className="text-[var(--md-text-secondary)]">{getFieldLabel('collection_city')}</dt>
                          <dd>{selectedJob.collection_city}</dd>
                          <dt className="text-[var(--md-text-secondary)]">{getFieldLabel('delivery_city')}</dt>
                          <dd>{selectedJob.delivery_city}</dd>
                          <dt className="text-[var(--md-text-secondary)]">{getFieldLabel('distance_km')}</dt>
                          <dd>{selectedJob.distance_km} km</dd>
                          <dt className="text-[var(--md-text-secondary)]">{getFieldLabel('required_vehicle_type')}</dt>
                          <dd>{selectedJob.required_vehicle_type ? getVehicleTypeLabel(selectedJob.required_vehicle_type) : '-'}</dd>
                          <dt className="text-[var(--md-text-secondary)]">{getFieldLabel('adr_required')}</dt>
                          <dd>{selectedJob.adr_required ? 'Yes' : 'No'}</dd>
                          {selectedJob.collection_time && (
                            <>
                              <dt className="text-[var(--md-text-secondary)]">{getFieldLabel('collection_time')}</dt>
                              <dd>
                                {new Date(selectedJob.collection_time).toLocaleString(undefined, {
                                  dateStyle: 'short',
                                  timeStyle: 'short',
                                })}
                              </dd>
                            </>
                          )}
                          {selectedJob.max_budget !== undefined && (
                            <>
                              <dt className="text-[var(--md-text-secondary)]">{getFieldLabel('max_budget')}</dt>
                              <dd className="font-medium">&pound;{selectedJob.max_budget.toFixed(2)}</dd>
                            </>
                          )}
                          {selectedJob.acceptable_vehicle_types && selectedJob.acceptable_vehicle_types.length > 0 && (
                            <>
                              <dt className="text-[var(--md-text-secondary)]">{getFieldLabel('acceptable_vehicle_types')}</dt>
                              <dd>{selectedJob.acceptable_vehicle_types.map(getVehicleTypeLabel).join(', ')}</dd>
                            </>
                          )}
                          {selectedJob.collection_window_minutes !== undefined && (
                            <>
                              <dt className="text-[var(--md-text-secondary)]">{getFieldLabel('collection_window_minutes')}</dt>
                              <dd>&plusmn;{selectedJob.collection_window_minutes} min</dd>
                            </>
                          )}
                          {(selectedJob.quote_count ?? 0) > 0 && (
                            <>
                              <dt className="text-[var(--md-text-secondary)]">{getFieldLabel('quote_count')}</dt>
                              <dd>{selectedJob.quote_count} received</dd>
                            </>
                          )}
                        </dl>
                      </div>

                      {/* Quote form */}
                      <div className="px-4 py-3">
                        <QuoteForm
                          job={selectedJob}
                          vehicles={vehicles}
                          drivers={drivers}
                          onSubmitted={handleQuoteSubmitted}
                        />
                      </div>
                    </div>
                    )
                  })()}
                </div>
                <QuoteHistory quotes={quotes} loading={quotesLoading} onRefresh={fetchProfileAndQuotes} onDeleteQuote={handleDeleteQuote} />
              </div>
            )}
            </div>
          ) : (
            <div className="space-y-4">
              <FleetProfile refreshTrigger={profileRefresh} />
              <FleetManagement
                vehicles={vehicles}
                drivers={drivers}
                onFleetChange={fetchProfileAndQuotes}
              />
            </div>
          )}
        </div>
      )}
    </div>
  )
}
