/**
 * UK location reference lists for the logistics platform.
 * Used by dirtyDataGenerator (dirty variants) and transformationService (canonical lists for fuzzy matching).
 */

/** Canonical UK city names - use these for location cleaning output */
export const UK_CITIES = [
  'London',
  'Manchester',
  'Birmingham',
  'Leeds',
  'Glasgow',
  'Liverpool',
  'Bristol',
  'Sheffield',
  'Edinburgh',
  'Cardiff',
  'Belfast',
  'Newcastle',
  'Nottingham',
  'Southampton',
  'Brighton',
  'Leicester',
  'Coventry',
  'Hull',
  'Bradford',
  'Stoke',
] as const

/** Dirty variants of UK cities (typos, wrong case, spaces) - used by dirtyDataGenerator */
export const UK_CITIES_DIRTY = [
  'london',
  'MANCHESTER',
  'Birmigham',
  'Leeds ',
  'Glasow',
  'Lverpool',
  'Bristol',
  'Sheffeild',
  'Edinbrugh',
  'CArdiff',
  'Belfst',
  'Newcstle',
  'Nottingam',
  'Southhampton',
  'Bighton',
  'Leicster',
  'Coventy',
  ' Hul ',
  'Bradfrord',
  'Stokee',
] as const

/** Canonical UK town names - use these for location cleaning output */
export const UK_TOWNS = [
  'Reading',
  'Slough',
  'Luton',
  'Northampton',
  'Derby',
  'Oxford',
  'Cambridge',
  'Ipswich',
  'Milton Keynes',
  'Swindon',
  'Peterborough',
  'Exeter',
  'Plymouth',
  'Bournemouth',
  'Blackpool',
  'Preston',
  'Burnley',
  'S Blackburn',
  'Bolton',
  'Wigan',
  'Warrington',
  'Chester',
  'Shrewsbury',
  'Hereford',
  'Gloucester',
  'Salisbury',
  'Portsmouth',
  'Maidstone',
  'Canterbury',
  'Dartford',
] as const

/** Dirty variants of UK towns - used by dirtyDataGenerator */
export const UK_TOWNS_DIRTY = [
  'Reading',
  'slough',
  'LUTON',
  'Nothampton',
  'Derby',
  'Oxfrord',
  'Cambrige',
  'Ipswich ',
  'Milton Keyes',
  'Swindn',
  'Peterbrough',
  'Exter',
  'Plymoth',
  'Bournmouth',
  'Black pool',
  'Preston',
  'Burnely',
  'S. Blackburn',
  'Boltn',
  'Wigan',
  'Warrington',
  'Chestre',
  'Shrewbury',
  'Hereford',
  'Glouster',
  'Salsbury',
  'Portsmouh',
  'Maidston',
  'Canterbry',
  'Dartfourth',
] as const
